package snake;

import java.awt.Color;
import java.awt.Graphics;

public class SnakePanel extends javax.swing.JPanel {

    private Snake snake;
    private final int TAM_CASILLA = 20;
    
    /**
     * Creates new form SnakePanel
     */
    public SnakePanel() {
        initComponents();
    }

    public void setSnake(Snake snake) {
        this.snake = snake;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        if(snake!=null) {
            for(int f=0; f<snake.getTamFila(); f++) {
                for(int c=0; c<snake.getTamCol(); c++) {
                    char contenido = snake.getTablero()[f][c];
                    switch(contenido) {
                        case Snake.VACIO:
                            break;
                        case Snake.CABEZA:
                            g.setColor(new Color(85,107,47));
                            g.fillOval(c*TAM_CASILLA, f*TAM_CASILLA, TAM_CASILLA, TAM_CASILLA);
                            break;
                        case Snake.CUERPO:
                            g.setColor(new Color(107,142,35));
                            g.fillOval(c*TAM_CASILLA+2, f*TAM_CASILLA+2, TAM_CASILLA-4, TAM_CASILLA-4);
                            break;
                        case Snake.MURO:
                            break;
                        case Snake.FRUTA:
                            break;
                    }
                }
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
